### ISSUE TITLE
Unable to run quickstart

### ISSUE THREAD

**Issue by surajsharma** [practicajs/practica#214]
I followed all the steps but on `npm start` i got this error:

```
npm start                                                                                                                                                              🔮  20:34:21

> order-service@0.0.2 start
> PORT=3000 PRETTY_PRINT=false node .dist/start.js

node:internal/modules/cjs/loader:361
      throw err;
      ^

Error: Cannot find module '/Users/admin/evenzero/s4NDb0x/default-app-name/node_modules/@practica/logger/.dist/logger.wrapper.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/admin/evenzero/s4NDb0x/default-app-name/services/order-service/.dist/start.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/admin/evenzero/s4NDb0x/default-app-name/node_modules/@practica/logger/package.json',
  requestPath: '@practica/logger'
}
npm ERR! Lifecycle script `start` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: order-service@0.0.2
npm ERR!   at location: /Users/admin/evenzero/s4NDb0x/default-app-name/services/order-service
```

OS: OSX 12.5.1
NODE: 16.15.0

**Comment by goldbergyoni** [comment]
@surajsharma On it! Let's make it work for you, I think that I found the issue. Will release a fix shortly, hopefully in 24 hours

Few q:

1. How did you install the project? Using our CLI with UI or without UI?
2. Which guide did you follow ("quick start" or "coding with practica")?

**Comment by surajsharma** [comment]
@goldbergyoni Thanks! 
1. I used the CLI with UI (`npx @practica/create-node-app interactive`)
2. I used "coding with practica" guide

**Comment by goldbergyoni** [comment]
@surajsharma I have a hypothesis why this happened and released a fix: v0.0.5

I can't be 100% sure that this issue is solved but the chances are quite good

Could you please try again?

Your feedback is important, highly appreciate if you can try again and let me know

While installing, please ensure that you're not pulling from the cache. You should not v0.0.5 in your package.json. If not, clean the local npm cache

**Comment by surajsharma** [comment]
@goldbergyoni so despite clearing the cache i'm still getting `0.0.2` in my `package.json` when i run `npx @practica`..

**Comment by goldbergyoni** [comment]
@surajsharma Can we please try:

1. Cleaning the npx cache explicitly:

``` rm -rf $(npm get cache)/_npx/*```

Works now?

2. Install explicitly the newer version:

```npx @practica/create-node-app@0.0.5 immediate --install-dependencies```

**Comment by surajsharma** [comment]
@goldbergyoni can confirm that this works as advertised, issue may be closed thanks!

**Comment by goldbergyoni** [comment]
Kudos 👌

Which step helped?

**Comment by surajsharma** [comment]
i think it was `npx @practica/create-node-app@0.0.5 immediate --install-dependencies` that did the trick
